### ISSUE TITLE
Oracle valuation method

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1279]
### Description

We want to be able to offer a new `ValuationMethod` for `pallet-loans`. This valuation will get the value from the outside through an oracle. 

### Research/based on

- [Slack: wg-oracle-valuation](https://kflabs.slack.com/archives/C050E3ZN2JU)
- [Requirements](https://centrifuge.hackmd.io/qcTAtX_9Q3WDXHRt1o9oJg?view)
- [Specs](https://centrifuge.hackmd.io/ayzluh1RR-aNWTZh6NMZ8g?view)

### Tracking

- [x] Write off triggers: #1305
- [x] Data Collection traits #1324
- [x] Implement `pallet-collection-data-feed`: #1324
- [x] Adapt `pallet-loans`: #1311
- [x] ~~Migration~~ => Not needed
- [ ] Add oracles to development runtime: #1377
- [x] ~~Add oracles to altair & centrifuge runtimes~~ => It's own future task
- [x] Fix benchmarks: #1372 
- [x] ~~Integration tests~~ => It's own task #1375
