### ISSUE TITLE
Feat: `ERC-20` Precompile for Balances

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#1726]
### Description
The `ERC-20` [precompile](https://github.com/moonbeam-foundation/moonbeam/tree/master/precompiles/balances-erc20) for balances is a needed step for using *Axelar ITS* and deprecating the existing chainbridge solution for bridging `CFG` to other domains. 

#### Tasks
* [ ] Add precompile to codebase
* [ ] Add new `DelegateCall`, etc. checks to precompile execution
* [ ] Make feature flag `forbid-evm-reentrancy` explicit 
  - Currently it is implicitly activated and we should be explicit about it to not have a silent breaking change

### Research/based on
* Needs to depcreate chainbridge as soon as possible

### How will this affect the code base
* Enable easy and UX-friendly cross-chain `CFG` transfers

### What are foreseen obstacles or hurdles to overcome?
* No migrations
* Need to adapt precompile logic to be secure - [see](https://medium.com/immunefi/moonbeam-missing-call-check-bugfix-review-6279d609bdc5)
