### ISSUE TITLE
Implement Centrifuge parachain's crowdloan feature

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#308]
**AS** a Polkadot/Kusama [parachain](https://wiki.polkadot.network/docs/en/learn-parachains) `Issuer` (e.g. Centrifuge)
**I WOULD LIKE** to launch a [crowdloan](https://wiki.polkadot.network/docs/en/learn-crowdloans) `Campaign`
**SO THAT** to get funds for acquiring a [parachain slot]() on Polkadot/Kusama [relay chain](https://wiki.polkadot.network/docs/en/learn-architecture#relay-chain).

## Acceptance criteria
- [ ] To invest in a crowdloan (or community-backed funding), a `Contributor` (or `Investor`) MUST lock tokens on Polkadot/Kusama [relay chain](https://wiki.polkadot.network/docs/en/learn-architecture#relay-chain) (i.e. DOT or KSM, respectively), hence **forgoing staking**.
- [ ] `Contributor`s MAY receive a reward payout, as a compensation for forgoing staking and for whetting investors' appetite to participate in an `Issuer`'s parachain project. 
- [ ] For a `Contributor` to claim a reward payout, the `Campaign` MUST be closed successfully. 
- [ ] For a `Contributor` to be eligible for a reward payout, she/he MUST prove her/his identity to the parachain.
- [ ] The rewarding mechanism MUST prevent replay attacks (i.e. if `Contributor` claim to be paid back. 

## Related stories:
#309 
#310 

## Estimate (in T-shirt size)
**XL**

## Risks
None

## References
[**Crowdloan Technical Specification**](https://centrifuge.hackmd.io/JIGbo97DSiCPFnBFN62aTQ#contributor-identity)
[**Crowdloan Reward Mechanism**](https://centrifuge.hackmd.io/NPmnf3a2R3SAN75nA-QSRw)
