### ISSUE TITLE
Implementing Reward Pallet

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#322]
# Description
Implementing the Reward Pallet. This Pallet is a Centrifuge specific Pallet that takes care of rewarding contributors of the crowdloan campaign. But might also be used in the future to reward contributors that helped the parachain to get another parachain slot in an auction.

# Functionality
- Providing initialization functionality (i.e. storing funds for rewards, blocking second init before the lease ends)
- Implement the Reward trait from the Claim pallet
- Reward contributors via some vesting logic (i.e. via vesting pallet or via own implementation)

# Open Questions
- *What to do when lease ends and users have not claimed yet?*
- *Vesting pallet will fail, when an account already has vesting in place*
      - Is this critical?
      - Does vesting implement this [design](https://substrate.dev/recipes/fixed-point.html#continuously-compounding)?
            IF NOT: Own implementation might be better.
- *How do we handle rewards under the min vested amount?*

# Tasks
- [x] Implementing Reward trait
- [x] Implementing dispatchable initialize function
- [x] Implementing simple rewarding transaction (i.e. no vesting or so, simply reward contributor with RADs for his contribution 1:1) 
- [x] Integrating vesting pallet
- [x] Unit test
- [ ] Implementing conversion from relay-to-native with a factor x, 0 <= x <= N 
- [ ] Testing implementation in local setup with claim module
    - [ ] Tests of arithmetic in local setup (e.g. are the conversions from relay chain to native balance correct)
- [ ] Benchmarking weights

# Branch 
https://github.com/mustermeiszer/centrifuge-chain/tree/feature/crowdloan%2FrewardPallet

**Comment by mustermeiszer** [comment]
@mikiquantum there are three things I am not sure about how we should handle them: 

- How do we handle a RewardAmount that is under the minimum amount necessary to vest? Currently, this is 1000*RAD.
- Unused balances of the module are current locked in the module. 
     Should we keep them there or create a hook that is triggered after the lease period is over and return them somewhere?

**Comment by vedhavyas** [comment]
@mustermeiszer 

> How do we handle a RewardAmount that is under the minimum amount necessary to vest? Currently, this is 1000*RAD.

I think this depends on the final ration we come up with in lieu with the minimum contribution amount.. I would suggest we define the ratios and minimum contribution in such a way that the final vesting amount is atleast minimum vesting amount. WDYT?

> Unused balances of the module are current locked in the module.
Should we keep them there or create a hook that is triggered after the lease period is over and return them somewhere?

We can leave them there. we can always transfer if we need to

**Comment by mustermeiszer** [comment]
> I think this depends on the final ration we come up with in lieu with the minimum contribution amount.. I would suggest we define the ratios and minimum contribution in such a way that the final vesting amount is atleast minimum vesting amount. WDYT?

Yes, I thing this will be the best way to handle this.
