### ISSUE TITLE
Implement claim module interface

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#323]
## Objectives

This issue aims at implementing the `Claim Module` interface, as defined in the [**Crowdloan Technical Specification**](https://centrifuge.hackmd.io/JIGbo97DSiCPFnBFN62aTQ).

## Tasks
- [x] Implement structural artefacts of `Claim Module`, namely trait, configuration, parameters, errors, events and storage
- [x] Implement dispatchable functions (or extrinsics)
- [x] Implement unit tests (mock runtime, relay chain's [crowdloan](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/crowdloan.rs) child-trie root hash, …)
- [x] Add `Claim Pallet` to Centrifuge runtime
- [x] Integrate with `Reward Pallet`
- [ ] Implement integration tests
- [x] Implement benchmarking for extrinsics weight information calculation

## Risks
- [x] Low: cross-messaging between relay- and para chain

## References
[**Crowdloan Technical Specification**](https://centrifuge.hackmd.io/JIGbo97DSiCPFnBFN62aTQ)
