### ISSUE TITLE
Enhance developer sandbox for virtualizing full fledged Polkadot ecosystem  

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#324]
## Objectives
In order to facilitate the testing and debugging of new features (such as pallets, for instance), this task aims at extending the [developer sandbox](https://github.com/centrifuge/centrifuge-chain/tree/master/tools/docker/sandbox) with a full fledged virtualised (using [Docker](https://www.docker.com/)) Polkadot/Kusama ecosystem, including Centrifuge chain as an onboarded parachain.
Among others, this enhancement will ease the testing of cross-chain messaging and also the benchmarking of the runtime. Moreover, new testing techniques for improving reliability of Centrifuge chain components should be implemented, such as fuzzing or property-based testing.

## Tasks
- [x] Check how to leverage on [polkadot-launch](https://github.com/paritytech/polkadot-launch) tool to build a virtualized environment.
- [ ] Create requisite Dockerfile and Docker Compose files
- [ ] Extend main Makefile

## Risks
None

**Comment by mustermeiszer** [comment]
Closed due to irrelevance.
