### ISSUE TITLE
Token Distribution

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-chain#327]
- [ ] Develop cli tool that creates vesting schedules with and without proxy account (internal token distribution vs token sale distribution)
- [ ] Execute internal distribution using this tool
- [ ] Execute token sale distribution using this tool
