### ISSUE TITLE
Adaption of the existing Vesting Pallet

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#337]
# Description 
Currently, the vesting pallet does not provide functionality that would allow the withdrawal of the right to vest from a user. This functionality is especially useful in terms of vesting schedules granted with respect to a contract that needs to be fulfilled.

# Changes
*Adapting the current `VestingInfo`struct:*
```rust
pub struct VestingInfo<Balance, BlockNumber, AccountId> {
        /// Controlling entitiy
        pub controller: Option<AccountId>
	/// Locked amount at genesis.
	pub locked: Balance,
	/// Amount that gets unlocked every block after `starting_block`.
	pub per_block: Balance,
	/// Starting block for unlocking(vesting).
	pub starting_block: BlockNumber,
}
```

*New dispatchable function:*
```rust
pub fn dissolve(origin, vester: <T::Lookup as StaticLookup>::Source, recipient: <T::Lookup as StaticLookup>::Source) {
    let controller = ensure_signed(origin)?;

    let target = T::Lookup::lookup(vester)?;
    let vesting = Self::vesting(&target).ok_or(Error::<T>::NotVesting)?;

    /// Ensure that controller has the right to dissolve
    if let Some(vest_controller) = vesting.controller {
         ensure!(vest_controller == controller);
    } else {
       /// Return error
    }
    
    /// Vest any not-yet-vested tokens to the vester
    update_lock(target);

    /// Remove rest of the vesting and transfer amount to the recipient
    
}
```

# Tasks
- [ ] Define changes to the storage
- [ ] Update Vesting info
- [ ] Update related functions
- [ ] Update tests to integrate features
- [ ] Define storage merge function
- [ ] Test in local setup

**Comment by mustermeiszer** [comment]
Not being done!
