### ISSUE TITLE
Port Centrifuge chain pallets to FRAME v2 procedural attribute-like macros

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#339]
## Objectives
Refactor all Centrifuge Chain pallets (and flanked libraries if needed, such as, `proofs`), so that they adhere to new FRAME v2 [attribute macros](https://crates.parity.io/frame_support/attr.pallet.html), rather than now obsolete function-like macros, such as, for instance, `decl_module`, `decl_event`, or `decl_error`.
We propose that each pallet refactoring being assigned to a sub-tasks of this story, so that to have a central place where to share, as this story will certainly spread several sprints, being a rather low-priority feature.

## Tasks
- [] Crowdloan `Claim pallet`.
- [] Crowdloan `Reward pallet`
- [x] `rad_claims` pallet (see #368 and #383)
- [x] anchors
- [] nft
- [] va_registry
- [] proofs 

## Risks
None

## References
[FRAME v2 pallet attribute macros](https://crates.parity.io/frame_support/attr.pallet.html)
[Rust attribute macros](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros)
