### ISSUE TITLE
Port `rad_claims` module to FRAME v2 macros

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#368]
## Objectives
Port the `rad_claim` pallet which actually is part of the Centrifuge chain runtime, to new FRAME v2's pallet attribute-based macros.

## Tasks
- [ ] Port `rad_claims` module to new FRAME v2 [macros](https://crates.parity.io/frame_support/attr.pallet.html)
- [ ] Extract `rad_claims` module from runtime into a more appropriate `pallets` folder
- [ ] Adapt, if necessary, the unit test cases
- [ ] Fork from [parachain]() branch.

## Risks
None

## References
[FRAME v2 Pallet Macros](https://crates.parity.io/frame_support/attr.pallet.html)
