### ISSUE TITLE
Port `bridge` pallet to FRAME v2 pallet macros

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#375]
## Objectives
Port the `bridge` pallet to new FRAME v2's pallet attribute-based macros.

## Tasks
- [ ] Port `bridge` module to new FRAME v2 [macros](https://crates.parity.io/frame_support/attr.pallet.html)
- [x] Adapt, if necessary, the unit test cases
- [ ] Set genesis config items using `parameter_types` macro
- [x] Adapt slightly [`chainbridge`](https://github.com/tankofzion/chainbridge-substrate/tree/refactor/bridge_pallet_frame_v2/chainbridge) pallet (not a full port to FRAME v2 macros) so that to compile with `bridge` pallet
