### ISSUE TITLE
Port 'nft' pallet to FRAME v2

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#388]
## Objectives
Port the `nft` pallet to new FRAME v2's pallet attribute-based macros.

## Tasks
- [ ] Port `nft` module to new FRAME v2 [macros](https://crates.parity.io/frame_support/attr.pallet.html)
- [ ] Adapt, if necessary, the unit test cases
- [ ] Set genesis config items using `parameter_types` macro
- [ ] Remove circular references to `va_registry` pallet's types using associated types
