### ISSUE TITLE
Implement `unique-asset-registry` pallet for NFT studio

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#482]
### Aims
A new registry for unique tokenized asset (also called non-fungible tokens) must be implemented for the [NFT Studio](https://centrifuge.hackmd.io/rF8epBlxQaWFvW-dN7XdAA) project.

### Tasks
- [ ] Implement `create_registry` extrinsic (including unit tests)
- [ ] Implement `transfer_ownership` extrinsic (including unit tests)
- [ ] Implement `remove_ownership` extrinsic (including unit tests)
- [ ] Implement `mint_nft` public module function (including unit tests)
- [ ] Implement `burn_nft` module function (including unit tests)
- [ ] Implement benchmarking for extrinsics

### Related Issues
#483 

### References
[Simple NFT Spec](https://centrifuge.hackmd.io/tzjNLdjfRfCfngApWNh0wQ)
[NFT Studio MVP Spec](https://centrifuge.hackmd.io/rF8epBlxQaWFvW-dN7XdAA)
