### ISSUE TITLE
Enhance `nft` pallet with new features required by the NFT Studio project

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#483]
### Aims
This issue aims at refactoring the existing [`nft` pallet](https://github.com/centrifuge/centrifuge-chain/tree/parachain/pallets/nft) so that to provide the necessary features to the new NFT Studio project. Among others, this enhanced `nft` pallet will provides a function (`generate_registry_id`) to generate chain-wide (globally) unique identifiers for registries (see #482), based on a nonce (i.e. a number which can be be used only once).

### Tasks
- [ ] Implement pallet primitives (i.e. types, traits, storage, ...)
- [ ] Implement/refactor `transfer_nft` extrinsic (including unit tests)
- [ ] Implement `mint_nft` public module function (including unit tests)
- [ ] Implement `burn_nft` public module function (including unit tests)
- [ ] Implement `new_registry_id` public module function (including unit tests)
- [ ] Implement benchmarking features

### References
[Simple NFT Spec](https://centrifuge.hackmd.io/tzjNLdjfRfCfngApWNh0wQ)
