### ISSUE TITLE
Runtime Specific Weights for Pallets

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#509]
In order to have a reasonable bench-bot, each runtime should have its own weights for every pallet included. See https://github.com/paritytech/polkadot/tree/master/runtime/polkadot/src/weights.

## Tasks
- [ ] ~~Integrate ALL (e.g. also balances, system, etc.) pallets we ware using in a runtime into the benchmark section of our runtimes, not just our costume ones~~
- [ ] ~~Bench Bot (to have a reasonable possibility to bench all pallets for a runtime upon changes See #510~~
- [ ] Runtime specific weights folder.

**Comment by mustermeiszer** [comment]
@mikiquantum and @NunoAlexandre. I think we should start working on this sooner than later! We are currently using the default weights for the pallets, but as we start to actually change some associated types with costume pallets (see collator selection) the weights of the extriniscs do not represent what we are actually doing. 

This will be a dangerous pitfall in the future.

**Comment by mustermeiszer** [comment]
Relates to the following issues and if done will close them:

- #582
- #578
