### ISSUE TITLE
POCC - Integration tests

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#617]
Tracking issue for POCC integration tests.

For POCC we want integration tests that allow us to test a runtime end-to-end from a business logic perspective. Of course, if the integration test also cover functional aspects like XCM this would be a plus.

# Tasks
- [x] Define framework [spec](https://centrifuge.hackmd.io/rjrBlcFnRN6oZdLPBajEIA)
- [x] Implement framework
- [ ] Define test-cases [spec](https://centrifuge.hackmd.io/tufaKxdTTKCnKZFGK734jw)
- [ ] Implement test-cases

# Test-Cases to Cover
- [ ] NAV stays 0, while a loan is issued but not borrowed from
- [ ] NAV behavior when a borrow happens really late before due-date
- [ ] Overall "debt" (i.e. capital generating interest) remains constant after rebalancing over epochs. Assuming, no more withdraw/deposit actions.

**Comment by mustermeiszer** [comment]
closing this for restructuring.
